### ISSUE TITLE
Please add compiling options

### ISSUE THREAD

**Issue by thecosss** [mrcrowl/vscode-easy-less#1]
It would be nice if i can do `//main:style.less` to compile the main file.
Also project-wide options like here https://github.com/jdiehl/brackets-less-autocompile would be cool to

**Comment by mrcrowl** [comment]
Nice! Hadn't seen that approach before. Will see what I can do.

**Comment by mrcrowl** [comment]
The options should now be available in v1.1.0.  Let me know how you get on.

**Comment by thecosss** [comment]
The description is a bit tricky for me. I have to main files master-desktop.less and master-mobile.less and a bunch of small files that are included to masters. I want to compile only these 2 master files every time i save for example 'header.less'

**Comment by mrcrowl** [comment]
To make sure I fully understand: could you send me a set of files to
demonstrate the problem you would like to address?

**Comment by thecosss** [comment]
[css.zip](https://github.com/mrcrowl/vscode-easy-less/files/130832/css.zip)
This is ongoing project. I'm making it with Brackets right now. I have 2 main files: style.less and mobile.less. So every time i save any of these 34 files i want to compile only 2 main files.

**Comment by mrcrowl** [comment]
I've now added support for multiple main files in v1.2.5.  See #5 on the [FAQ](https://github.com/mrcrowl/vscode-easy-less#faq) for more detail.  One thing to be aware of right now is that the main files when specified in settings.json are relative to the file being saved (which is not _ideal_).  So it may be best to use the per file option for now.
