### ISSUE TITLE
Not using latest version of Less

### ISSUE THREAD

**Issue by danloughmiller** [mrcrowl/vscode-easy-less#103]
lessc now supports @container queries, but extension uses older version even if newer version is installed on the system

**Comment by mrcrowl** [comment]
Hi Daniel,

Good spotting. Are you in a position to make a pull request? Just not sure
how quickly I’ll get around to making this change.

Best

**Comment by danloughmiller** [comment]
I wish I was more familiar with updating such things because I'd hope it's as simple as updating the dependency, but doing that locally didn't seem to fix things so this one is out of my skillset

**Comment by mrcrowl** [comment]
Okay, so you managed to fork/clone the repo and then updated the less
dependency in package.json… is that right?

If you start a branch with the change and make a pull request, I’m happy to
work with you on getting the rest done.

**Comment by danloughmiller** [comment]
Believe I managed to create a pull request from a fork where I updated the dependency

**Comment by mrcrowl** [comment]
Thanks! Looking great. 

Do you have a small snippet of `.less` code that would help me to verify if the new version is being used?

**Comment by danloughmiller** [comment]
Sure, so when a container query is nested inside another selector, such as:
```
.a {
  @container (max-width:600px) {
    .b { color: blue;}
  }
}
```

prior versions of Less will lose the parent context, e.g.
```
@container (max-width:600px) {
  .b {
    color: blue;
  }
}
```

4.2+ will correctly include the parent selector in the container query, similar to how @media works.

```
@container (max-width: 600px) {
  .a .b {
    color: blue;
  }
}
```

**Comment by mrcrowl** [comment]
Updated to less 4.2.0 (including container query support) in v2.0.2
