### ISSUE TITLE
How do I supress compiling this less file / compile  different less files than the one being edited?

### ISSUE THREAD

**Issue by zphhhhh** [mrcrowl/vscode-easy-less#14]
Here I have some more than one .less files,  and them all depend on a _colors.less file.
So I want to get it that if I edit the _colors.less file, the others who depends it should be recompiled.

Below the Code is not correct :
```
// main: ['./nav.less', './home.less']
```
Thank you!

**Comment by mrcrowl** [comment]
Unfortunately, easy-less doesn't currently track @import references from other less files.

But you can achieve what you want by referencing each dependent file as a "main":

`//` main: ./nav.less, main: ./home.less`
