### ISSUE TITLE
Calc Errors on Compile

### ISSUE THREAD

**Issue by jgwhitley1017** [mrcrowl/vscode-easy-less#15]
There seems to be an issue using variables with Calc.  For Example, in the below code, you would expect height to be calc(100% - 92px), but it renders as calc(8%).

```
@sample-height: 92px;
div.foo {
  height: calc(100% - @sample-height)
}
```

**Comment by mrcrowl** [comment]
Yes, this is a [known problem](http://stackoverflow.com/questions/17904088/disable-less-css-overwriting-calc) with less .
