### ISSUE TITLE
This command only works for .less files.

### ISSUE THREAD

**Issue by sagive** [mrcrowl/vscode-easy-less#17]
Hey, 
after the last update i have been getting this in last files
"This command only works for .less files."

This happens when using a less file ofcourse (when would this message apear otherwise?)
i dont know if this is a bug 

This is my settings (worked before update):
```
     "less.compile": {
         "compress":  true,  // true => remove surplus whitespace
         "sourceMap": true,  // true => generate source maps (.css.map files)
         "out":       true // false => DON'T output .css files (overridable per-file, see below)
    },
```

Even when trying to directly compile the file (f1 compile LESS to CSS)
i am getting "This command only works for .less files."

File name is "main.less"

**Comment by mrcrowl** [comment]
I have seen this message when saving multiple files at the same time (e.g.
Save all)

Would this be likely in your case? Or does it occur even when saving just a
single file.

Either way, it's a bug that should be fixed.

**Comment by sagive** [comment]
i am only saving one file (only one file open)... Currently can't use this plugin (which i love! ;) )
Anything i can do?

I am using VScode, is there a workaround? 
Can i install a previos version? Is there a way to manually install an older version?

**Comment by mrcrowl** [comment]
Here's the [previous version](https://www.dropbox.com/s/2xkig0et5vgw82b/easy-less-1.4.1.vsix?dl=0) as a .vsix file.

You can install via Extensions > Triple dot menu > Install from vsix

**Comment by mrcrowl** [comment]
I've tried, but I can't repro this issue you're describing.  Are there any other extensions you've installed recently that might have affected this?

**Comment by sagive** [comment]
Thank you very much for the quick response and the awesome extension.  ;) 

I already left the office. But... i just upgraded at home, had the same problem, restarted VScode - (not "reload" < clicking that button didnt help) and now it WORKS ;))

**Comment by mrcrowl** [comment]
@sagive are you happy for this issue to be closed?
