### ISSUE TITLE
How to compile to .css and .min.css

### ISSUE THREAD

**Issue by brianeunilkim** [mrcrowl/vscode-easy-less#18]
It would be great if it was possible to generate uncompressed .css and compressed .min.css file on .less file save. 
I couldn't find the option to do this.

**Comment by mrcrowl** [comment]
@brianeunilkim interesting suggestion, and yes, something that it not currently possible. 

Can you help me to understand the situation in which you want to output both .css and .min.css, each time you save a file?

**Comment by mrcrowl** [comment]
Closing for now due to inactivity.
