### ISSUE TITLE
Rename variable in all files

### ISSUE THREAD

**Issue by DifficultNick** [mrcrowl/vscode-easy-less#19]
Is there any way to rename _@variable_ (definition and references) in all files of workspace?

**Comment by mrcrowl** [comment]
Yes, while this would certainly be a nice feature, renaming of a variable across files is currently outside the scope of what this extension aims to be.  The renaming of variables within a single .less file is currently something built into vs-code.

Though, if you were willing to submit a PR for this feature, I would be more than happy to consider it.  It looks like [languages.registerRenameProvider](https://code.visualstudio.com/docs/extensionAPI/vscode-api#languages.registerRenameProvider) is the extension point you'd be interested in.
