### ISSUE TITLE
Compile Less to CSS

### ISSUE THREAD

**Issue by pnkr** [mrcrowl/vscode-easy-less#2]
i have installed the extention in VS Code but i cant figure out how to work it.

in my template.less file i added the following at the beginning

// out: template.css, compress: true, sourceMap: false

But on file save nothing happens.
also if i press F1 and type compile LESS to CSS there is an error:
**No handler found for the command: 'easyLess.compile'. Ensure there is an activation event defined, if you are an extension.**

**Comment by mrcrowl** [comment]
Thanks so much for letting me know about this.  I wasn't aware because it continued to work on my local machine fine.

Fixed in v1.2.0+

**Comment by pnkr** [comment]
Thanks for the immediate response!
It now works great!

One of the most usefull plugins in the repository of VS Code.
