### ISSUE TITLE
Declaring Constants

### ISSUE THREAD

**Issue by den4ik-webdev** [mrcrowl/vscode-easy-less#23]
File `/out/src/LessCompiler.js

[LessCompiler.js.txt](https://github.com/mrcrowl/vscode-easy-less/files/1015961/LessCompiler.js.txt)

How is this possible?

And because of this, no link to sourceMap file.
Revise the declaration of the constants in the given code place.
Thank you!

**Comment by mrcrowl** [comment]
This should be fixed by v1.4.4 now released.
