### ISSUE TITLE
Source maps not working

### ISSUE THREAD

**Issue by peters4oz** [mrcrowl/vscode-easy-less#26]
Source maps were working for my install and now they are not - this is for both embedded and separate source map files.  The compiler produces the source map but it doesn't work in the browser.  Using version 1.4.3 Easy LESS in VSCode 1.12.2.

Testing the LESS file in another compiler (Crunch 2) and the source maps are much larger but they do work.

I have attached the LESS, CSS and Source Map for each compiler.

[crunch2LESS.zip](https://github.com/mrcrowl/vscode-easy-less/files/1046261/crunch2LESS.zip)
[EasyLESS.zip](https://github.com/mrcrowl/vscode-easy-less/files/1046263/EasyLESS.zip)

**Comment by mrcrowl** [comment]
Apologies for the delay. Fix coming in v1.4.4 soon.
