### ISSUE TITLE
Generate both a *.css and a *.min.css file from the same file?

### ISSUE THREAD

**Issue by toddhd** [mrcrowl/vscode-easy-less#28]
How I can setup settings.json so that each *.less file is compiled twice? Once as a *.css file and once as a compressed *.min.css file?

**Comment by mrcrowl** [comment]
Hi @toddhd, issue #18 also asked for this, but I didn't get a compelling enough answer about what the use case was.

Can you help me understand what the use-case is for wanting both generated?

**Comment by kwilliams1987** [comment]
The use case is having the *.css referenced during development and *.min.css referenced in production.

**Comment by Paul-Hebert** [comment]
@mrcrowl I had a similar use case. I ended up compiling the minified version during my overall build process, but it does seem nice to have right out of the box.
