### ISSUE TITLE
Also compile files referencing to saved file

### ISSUE THREAD

**Issue by cpaderbarosch-tgm** [mrcrowl/vscode-easy-less#29]
If you have, for example a `index.less`:
```
@import "vars.less"

body {
  color: @color-primary;
}
```

and a `vars.less`:
```
@color-primary: #FFF;
```

It would be great, when I change something in the `vars.less`, if the `index.less` would also get compiled.

**Comment by BaamAadmi** [comment]
+1  
I am also trying to figure out the same. I have been using grunt/gulp for a long time. But now since angular ts, its not needed anymore and not cool to use grunt only for LESS -> CSS.

Thanks in advance.
-Sudeep

**Comment by Paul-Hebert** [comment]
+1
Web Essentials for Visual Studio handles this. I'm trying to configure something similar for VsCode. Right now I need to manually go and save the parent LESS file every time.

**Comment by MarkBird** [comment]
Hi, I think what you are looking for is to add a comment to the top line of the vars.less file:

// main: index.lass

Then if you change vars.less, index.less will also be compiled and your change should appear in index.css.

**Comment by Paul-Hebert** [comment]
Thanks @MarkBird! I'll try it out soon.
