### ISSUE TITLE
HEX color autoreplacment should not be the default behavior

### ISSUE THREAD

**Issue by thecosss** [mrcrowl/vscode-easy-less#3]
I'm trying to switch to VSCode now in my project. I've test-compiled my styles and saw this stuff in my diff

```
-  color: #ffffff;
+  color: #fff;
-  background: linear-gradient(to bottom, #f17a4c, #ef6262);
+  background: linear-gradient(to bottom, #F17A4C, #EF6262);
```

I think that should not be the default behavior, Easy Less should compile hex colors as is by default.
Everything else is seem to be working fine.

**Comment by mrcrowl** [comment]
That's very interesting.  I can't easily reproduce the issue on my side.
I've just tried now with a one-file example, and it appears to preserve
them hex colors as typed.

Can you send me an isolated example where you are seeing this issue occur?

**Comment by mrcrowl** [comment]
Also, are you seeing diff changes to the *css* or the *less* files?

**Comment by thecosss** [comment]
I'm seeing diff changes in CSS files.

**Comment by mrcrowl** [comment]
@thecosss, feel free to open this issue with an example that I can look into.
