### ISSUE TITLE
Wrong compile

### ISSUE THREAD

**Issue by MonFig** [mrcrowl/vscode-easy-less#30]
Will compile `calc(100vh - 10vw)` into `calc(90vh)`

**Comment by gprasanth** [comment]
this is an upstream issue and not an issue of vscode-easy-less itself.

see the following issues:

https://github.com/less/less-docs/issues/441
https://github.com/less/less.js/issues/1880

work around would be to use: `calc(~"100vh - 100vw")` which gives the intended output.
