### ISSUE TITLE
grunt less task 'modifyVars'

### ISSUE THREAD

**Issue by heekei** [mrcrowl/vscode-easy-less#31]
gruntfile.js:
![image](https://user-images.githubusercontent.com/10609199/32358566-0860fd22-c082-11e7-9d8b-33aef9280fcc.png)
.less:
![image](https://user-images.githubusercontent.com/10609199/32358574-1db0e318-c082-11e7-9e1d-61a0d02945e8.png)
it cant be compile.

**Comment by mrcrowl** [comment]
Easy-LESS has no connection to grunt, sorry.
