### ISSUE TITLE
report compiler errors 

### ISSUE THREAD

**Issue by kineodavid** [mrcrowl/vscode-easy-less#33]
Hi, I'm not sure if I'm using this plugin correctly, but it doesn't see to report any compiler errors to the user.
Is there a want to turn on compiler errors?

Thanks David

**Comment by NonTestatum** [comment]
Hi, I'm also have that problem

**Comment by mrcrowl** [comment]
You should see an compilation errors in the _Problems_ pane.  Although this is only the case for .less files that are currently open.

![image](https://user-images.githubusercontent.com/1796256/46733507-0a7bc880-cced-11e8-8d06-00531aa12374.png)
