### ISSUE TITLE
Compile 'out' target not respected

### ISSUE THREAD

**Issue by advnodequest** [mrcrowl/vscode-easy-less#34]
I have a folder structure like this, (starting from my project's workspaceRoot):
work > less
wwwroot > assets > css

In my settings.json, I have:
` "out": "${workspaceRoot}\\wwwroot\\assets\\css\\"`

I also tried:
` "out": "${workspaceRoot}/wwwroot/assets/css/"`

However, when I save, the compiled files are created in the **less** folder instead of the out target. 
My platform is Windows.
 How can I get Easy-less to compile to the specified folder?

**Comment by chriswarr** [comment]
I have the same problem.

**Comment by chriswarr** [comment]
I fixed the problem for me.  I also had a // out directive at the top of my .less files, these override the one in settings.json.  So just delete them from your .less files.

**Comment by advnodequest** [comment]
@chriswarr nailed it
