### ISSUE TITLE
Compiler calculation issue

### ISSUE THREAD

**Issue by ArnoutPullen** [mrcrowl/vscode-easy-less#35]
with less:
`width: calc(100% + 48px);`

is compiled to css:
`width: calc(148%);`

**Comment by ArnoutPullen** [comment]
found a solution:
`width: ~"calc(100% + 48px)";`

**Comment by yume-chan** [comment]
It's unrelated to this extension, it's how the LESS compiler works. Use `~"calc(100% - 10px)"` is the official way to avoid interpolation.
