### ISSUE TITLE
Relative path to .less file, goes two directories up

### ISSUE THREAD

**Issue by marcing** [mrcrowl/vscode-easy-less#38]
Following code does not look for theme.less in correct directory.
Instead of parent directory, it looks for it in parent of parent.

 "less.compile": {
        "main": ["../theme.less"], 
    } 

Cheers

**Comment by DifficultNick** [comment]
If `settings.json` in parent directory contains `"main": ["./style.less"]` then files in subdirectory are using `./parent/sub/style.less` instead of `./parent/style.less`.

It would be great if it would be solved

**Comment by mrcrowl** [comment]
In this situation, I would recommend using the `${workspaceRoot}` variable in your `main` setting. e.g.

```
{    
    "less.compile": {
        "main": "${workspaceRoot}/style.less"
    }
}
```
