### ISSUE TITLE
EASY LESS

### ISSUE THREAD

**Issue by pujarasanni027** [mrcrowl/vscode-easy-less#40]
Hello Team,

I have implemented easy less working fine with respected variable values.

can i change those (variable's)  value dynamically from code  (Typescript) side.

Will it dynamically update less file ?

Need help.

Thanks

**Comment by mrcrowl** [comment]
Hi @pujarasanni027 ... I'm not sure I _entirely_ understand what you're meaning, but I'll give it a go.

The only way that EasyLESS converts from less --> css is when a file is saved inside of vs code.  It doesn't detect changes to the file that are triggered outside of that process.
