### ISSUE TITLE
sourceMap another file

### ISSUE THREAD

**Issue by haoss** [mrcrowl/vscode-easy-less#43]
I have settings

"less.compile": {
        "sourceMap": true, // true => generate source maps (.css.map files)
        "compress": true, // true => remove surplus whitespace
        "out": "../style.min.css", // false => DON'T output .css files (overridable per-file, see below)
        "main": "all.less",
        "sourceMapFileInline": false
    }

and in style.min.css a see /*# sourceMappingURL=./all.css.map */

all.css.map !!! not style.min.css.map

The only solution is to use the sourceMapFileInline setting.

**Comment by mrcrowl** [comment]
Fixed in v1.6.3
