### ISSUE TITLE
compile errors with calc expression

### ISSUE THREAD

**Issue by UtillYou** [mrcrowl/vscode-easy-less#45]
I have an expression in less:
```less
height: calc(100% - 38px);
```

output css with:
```less
height: calc(62%);
```

**Comment by gibriil** [comment]
I ran into the same issue. You need to escape the code. `height: ~"calc(100% - 38px)";`

**Comment by UtillYou** [comment]
> I ran into the same issue. You need to escape the code.
> `height: ~"calc(100% - 38px)";`

That works. Is this a bug? It works normally when I use other less compiler.

**Comment by gibriil** [comment]
I honestly can't speak to whether or not this is a bug. I believe it has something to do with the method of compiling. If you use an online compiler like https://lesstester.com/ you have to do the same type of escaping.
