### ISSUE TITLE
please update the less version

### ISSUE THREAD

**Issue by linxz** [mrcrowl/vscode-easy-less#47]
```
"dependencies": {
    "less": "2.7.2",
    "mkpath": "^1.0.0",
    "less-plugin-autoprefix": "^1.5.1"
  }
```

The latest version of less is 3.9.0.
Hope to rely on the latest version, thank you

**Comment by docguytraining** [comment]
Please update to latest LESS version. I need to be able to use features from 3.5.0 (released 15 months ago at this point). Specifically: Namespaced Values / Maps e.g. color. For example:
`
@title-size: (@p-size * 2); //32px
@title-size-print: 24pt; //24pt
@p-size: 16px;

#library() {
    .sizes() {
        h1: (@title-size - 2); //30px
        h1p: (@title-size-print - 2);
        h2: (@title-size - 5);
        //etc.
    }
  }

h1 {
    font-size: #library.sizes[h1];
  }
@media print { 
      h1 {
          font-size:#library.sizes[h1p];
           }
}`

Currently this doesn't work.

**Comment by mrcrowl** [comment]
Sorry for the delay folks.  v1.5 now has been updated to v3.9 of less.
