### ISSUE TITLE
compile less

### ISSUE THREAD

**Issue by didzis-griezans** [mrcrowl/vscode-easy-less#48]
Recently stoped working and started trowing errors about my mixins.

._text(16px,20px)

![image](https://user-images.githubusercontent.com/5363595/59767138-50405600-92aa-11e9-97a7-ec46163c68a8.png)
etc

**Comment by mrcrowl** [comment]
Is the mixin in the same file or imported?

**Comment by mrcrowl** [comment]
Closing until I can get some repro steps, or further details about the errors that are being generated.
