### ISSUE TITLE
Workspace with multiple projects -> Settings for each project folder?

### ISSUE THREAD

**Issue by jjnxpct** [mrcrowl/vscode-easy-less#50]
Hi! We have some project folders that use the easy less compiler. These all work fine. But when we open those folder in a single workspace, the individual folder settings.json , containing our less.compile settings, are ignored. 

Is it possible to have multiple project in a VSCode workspace that also have individual settings for the easy less plugin? 

We could add a 'global' workspace setting, but that would mean we have to use the same settings for all projects/folders in the workspace. We would like to be able to maintain the folder settings.

**Comment by shijue98** [comment]
I have the same question

**Comment by mrcrowl** [comment]
The issue with settings in multi-project workspaces should be resolved as of [v1.6.0](https://github.com/mrcrowl/vscode-easy-less/releases/tag/v1.6.0), released today.
