### ISSUE TITLE
Unable to compile less with inline JS

### ISSUE THREAD

**Issue by kranack** [mrcrowl/vscode-easy-less#54]
Since the new version `1.5.0`, it appears my less cannot compile anymore.

This is the error i get in VSCode
![image](https://user-images.githubusercontent.com/2787828/67213434-4d9f6a00-f41e-11e9-8189-cfc961cb5c92.png)

Is there an option to add in `less.compile` to make it work ?

**Comment by mrcrowl** [comment]
Thanks for the feedback.  The option `javascriptEnabled` has been added in v1.5.1 to address this.  

Looks like they moved this from default behaviour in LESS v3
