### ISSUE TITLE
less转wxss时,会把less引入的其他文件样式全部编译到less中

### ISSUE THREAD

**Issue by CCdingxin** [mrcrowl/vscode-easy-less#57]
引入外部字体在less中,less生成wxss时会将字体文件内容全部编译到wxss中  导致wxss文件过大 请问有什么方法可以避免么 谢谢

**Comment by mrcrowl** [comment]
WXSS is not explicitly supported by this extension, which focuses on standard LESS. 

Consider opening an issue in [Easy WXLESS](https://marketplace.visualstudio.com/items?itemName=yunfeizuo.easy-wxless) which was forked from repo.
