### ISSUE TITLE
command 'easyLess.compile' not found

### ISSUE THREAD

**Issue by zf-1** [mrcrowl/vscode-easy-less#58]
hi, when I try to compile less I get the message "command 'easyLess.compile' not found", although the extension is enabled

**Comment by mrcrowl** [comment]
Thanks for reporting. Is this happening when you have a .less file open and hit Ctrl+S/Cmd+S or are you choosing _Compile Less_ from the command palette?

The command should be activated (made available to vscode) as soon as you open a .less file.

**Comment by mrcrowl** [comment]
... also, can you include a screenshot of this happening, please, to provide more context.

**Comment by zf-1** [comment]
when i save the file just nothing happens. This message appears exactly when I run the command through the panel
![изображение](https://user-images.githubusercontent.com/19506637/72493087-54c0f300-3828-11ea-9b53-c1863a362e8a.png)

**Comment by zf-1** [comment]
![изображение](https://user-images.githubusercontent.com/19506637/72493485-d82f1400-3829-11ea-92af-7f8e062d8b76.png)
just in case

**Comment by mrcrowl** [comment]
What version of vscode and which OS?

**Comment by zf-1** [comment]
vscode 1.41
windows 10 (1909, build 18363.535)

**Comment by mrcrowl** [comment]
Does your Output panel show any messages under the Extensions group?

![image](https://user-images.githubusercontent.com/1796256/72640177-30058080-39cc-11ea-8c8a-2b0646de1fbe.png)

**Comment by zf-1** [comment]
I don’t know what this is connected with, but the problem solved itself. everything works again. thanks for the help.
![изображение](https://user-images.githubusercontent.com/19506637/72780738-43148c80-3c28-11ea-9b44-f164b06faff8.png)
