### ISSUE TITLE
main support reg?

### ISSUE THREAD

**Issue by Dailoge** [mrcrowl/vscode-easy-less#59]
I want to set many main file, but i don't kown how solve it

**Comment by mrcrowl** [comment]
This is supported. Information on how is covered in point 6 of the [FAQ](https://marketplace.visualstudio.com/items?itemName=mrcrowl.easy-less#faq).

**Comment by Dailoge** [comment]
I don't understand; i have many main file, for example:
pages/index/index.less
pages/detail/index.less
page/personal/index.less
and more...

how should i write?

**Comment by mrcrowl** [comment]
First, to clarify, "main" file just means _a file that `@imports` other less files_.

If you _always_ want to compile all of the above files every time any .less file is saved, then edit the JSON file for your user settings, and add:
```
{    
    "less.compile": {
        "main": ["pages/index/index.less", "pages/detail/index.less", "pages/personal/index.less"]
    }
}
```

If you only want to update certain main files when specific imported less files change, then you can add a comment to the top of the imported file:

e.g. imagine a file at: `pages/index/anchors.less`. It could contain the following `main` directive:
```
// main: ../../index.less

a { text-decoration: none }
```

**Comment by mrcrowl** [comment]
... Easy LESS doesn't automatically figure out which main files should be compiled. i.e. it doesn't detect `@import` statements in other files.  You have to tell it where the other files are that import the "child" file.

**Comment by Dailoge** [comment]
ok, I know, thanks
You're really great, man

**Comment by Dailoge** [comment]
i have another issue, how should i write 'out' and 'main' comment to the top of the imported file;
i try 
```
// out: true
// main: index.wxss
html {
  body {
    margin: 0px;
  }
}
```
but it not work, i need your help, thanks

**Comment by mrcrowl** [comment]
All directives must be on a single line at the top of the file, comma separated:
```
// main: index.wxss, out: true

html {
  body {
    margin: 0px;
  }
}
```

**Comment by Dailoge** [comment]
In this way, it still doesn't work
