### ISSUE TITLE
Stopped working - no output

### ISSUE THREAD

**Issue by geri777** [mrcrowl/vscode-easy-less#6]
I have installed easy-less some days ago and it worked. Today I have changed my .less file again, but there is no console output and no css file is written. Can I debug/test somehow what's going wrong?

VS-Code: 1.2.1
easy-less: 1.2.5

**Comment by mrcrowl** [comment]
Yes, you can always fork the extension and run it from vscode in debug mode.   Let me know if you'd like further details.
