### ISSUE TITLE
How to use other plugin?

### ISSUE THREAD

**Issue by tianyiw2013** [mrcrowl/vscode-easy-less#63]
I want to use less-plugin-glob, I don't know how to set it up.
Help me, thank you

less-plugin-glob:
https://github.com/just-boris/less-plugin-glob

**Comment by mrcrowl** [comment]
Sorry, there isn't support for custom plugins at the moment. 

In theory, you _could_ work around this by copying the plugin into your extensions folder -- but this is something I haven't really experimented with much. On windows, this is something like:
`%userprofile%\.vscode\extensions\mrcrowl.easy-less-1.6.3\node_modules\`
