### ISSUE TITLE
How do I cross-file code prompts

### ISSUE THREAD

**Issue by dakezuo** [mrcrowl/vscode-easy-less#65]
Such as:
In file A @main-color;
ImportA in B file;
But there is no active code prompt when using @main-color in a B file

**Comment by mrcrowl** [comment]
Hi, this autocomplete for LESS is part of the LESS language plugin which is built-in to vs-code itself, and not really related to EasyLESS. 

I suggest [filing an issue with vscode](https://github.com/microsoft/vscode/issues).
