### ISSUE TITLE
Folder in folder

### ISSUE THREAD

**Issue by kevadamson** [mrcrowl/vscode-easy-less#72]
Settings:

```
{    
    "less.compile": {
        "main": [
            "layout.less",
            "admin.less",
        ]
    }
}
```

I have a folder inside my CSS folder with some partials that get included in layout.less, but the build errors as it is looking for layout.less and admin.less inside that additional folder as well. I've got around this by placing empty layout and admin less files in this folder, but is there a better way of doing this?

**Comment by kevadamson** [comment]
![files](https://user-images.githubusercontent.com/1021744/104968607-3c0c8f80-59de-11eb-8272-f9a2e818d4cd.png)

This is the folder structure btw

**Comment by mrcrowl** [comment]
Can you please provide a small sample repo that reproduces the bug? This will make it easy to debug.
