### ISSUE TITLE
Can't import, css files into styles.less

### ISSUE THREAD

**Issue by kasske** [mrcrowl/vscode-easy-less#73]
Used to import files like this: @import '../css/vendor/bootstrap.min.css';
Now, with the latest version, I can't import framework files into styles.less

I downgraded extention and seems to work on it.

**Comment by cri-matt** [comment]
Same here. Our team had to downgrade to the previous version as well.

**Comment by corporatereports** [comment]
Also having this issue. Downgrading works.

**Comment by mrcrowl** [comment]
Sorry about this. Fixed in v1.7.1
