### ISSUE TITLE
Version 1.7.1 no longer compiles mathematical operations

### ISSUE THREAD

**Issue by cri-jon** [mrcrowl/vscode-easy-less#74]
I'm trying to use width: 100% / 3; and it no longer compiles correctly. The compiled css still says width: 100% / 3; Thanks for looking into this.
![Screen Shot 2021-01-29 at 9 14 28 AM](https://user-images.githubusercontent.com/51245636/106285386-6ba76d00-6212-11eb-8c39-6688bb3f247e.png)

**Comment by corporatereports** [comment]
This is happening for me too.

**Comment by mrcrowl** [comment]
Ah, sorry. This should have been advertised as a breaking change in the release notes.

The less compiler changed the default `math` mode to `parens-division` in v4.x. 

To restore the v3.x behaviour you will either need to:
 * set the `math` mode to `"always"` (probably best in the settings file for a global change); or...
 * wrap the expression with parentheses to force the division, i.e. `width: (100% / 3)`

See 
 * http://lesscss.org/usage/#less-options-math
 * https://github.com/mrcrowl/vscode-easy-less/#project-wide--global-configuration

**Comment by mrcrowl** [comment]
I've updated [the changelog](https://playbooks.codelingo.io/p/p_EMdmk2e) to reference this change in behaviour.
