### ISSUE TITLE
can vscode-easy-less do not compil @import ".*less"？

### ISSUE THREAD

**Issue by zzh3319** [mrcrowl/vscode-easy-less#78]
like a  comment between   
`not-compiling
@import "./c.less";
not-compiling`
it will not compil it；

but out of commint it can compil as before；

**Comment by mrcrowl** [comment]
Sorry, I'm not sure I understand the question.

The title of this issue (wildcards?) seems to differ from the body which is about comments ... have I got that right?

**Comment by mrcrowl** [comment]
Closing due to no response
