### ISSUE TITLE
Support for Group CSS Media Queries

### ISSUE THREAD

**Issue by docguytraining** [mrcrowl/vscode-easy-less#79]
I love this plugin. Would you consider a feature request? I'd love it if you could include the group-css-media-queries extension and provide easy support for it.

https://github.com/Se7enSky/group-css-media-queries

Thanks for a great plugin!

**Comment by mrcrowl** [comment]
Thanks for the idea, but I'm trying to keep this plugin as simple as possible. The extension you've mentioned looks cool, but is outside the core feature set that most people will need.
