### ISSUE TITLE
Support for wildcarding in less.compile.out specification?

### ISSUE THREAD

**Issue by shayping** [mrcrowl/vscode-easy-less#8]
I have my css and less files stored in different directoeis e.g
root/css/a.css b.css q.css  
root/less/a.less b.less c.less .... z.less

I don't see how I can configure less.compile to save the css in different directory without fully  describing 
every single file path in main and out.

Instead I would love to write
"less.compile" : {
  "out" : "../css/*.css"
}

**Comment by mrcrowl** [comment]
Although you can't use wildcards, if your situation is as straightforward as you've detailed above, then you can now use the `folderPath` of the `out` parameter.   See https://github.com/mrcrowl/vscode-easy-less/blob/master/README.md#settings.  

If this works for you, can you please close the issue?

**Comment by mrcrowl** [comment]
Closing issue because I didn't receive any further feedback.
