### ISSUE TITLE
Add $1 and $2 in filename

### ISSUE THREAD

**Issue by satiromarra** [mrcrowl/vscode-easy-less#81]
The output filename may contain $1 or $2, which will be replaced by the input baseFilename and extension, respectively. 
So a file named style.less and is configured with `// out: $1.$2.css` will compile to style.less.css.

In the file LessCompiler.ts change:
```
const interpolatedOut = intepolatePath(out, lessFile);
```

to:
```
const interpolatedOut = intepolatePath(out.replace('$1', baseFilename).replace('$2', extension), lessFile);
```

**Comment by mrcrowl** [comment]
Sounds great! Happy to submit a PR?

**Comment by satiromarra** [comment]
Done!

**Comment by mrcrowl** [comment]
Thanks. LGTM and merged.
