### ISSUE TITLE
Possible issue with calculations inside unit()/percentage()

### ISSUE THREAD

**Issue by krsdcbl** [mrcrowl/vscode-easy-less#83]
Hello,

I am recently encountering the errors `Error evaluating function unit: the first argument to unit must be a number. Have you forgotten parenthesis?` and `Error evaluating function percentage: argument must be a number` when compiling my LESS files with this extension.

Experimenting around a bit, this seems to be due to instances when I use a calculation directly in the function without wrapping it in parentheses, like: `prop: unit( 1 / 2, rem);` instead of `prop: unit( ( 1 / 2 ), rem);`.

Yet this is the only compiler I'm using throwing these errors, so far tested with @zeit/next-less as well as official http://lesscss.org/less-preview/, and they will take code without the extra parentheses just fine. Might this be a case of other compilers handling the spec too loosely, or is this a possible bug?

Thanks & all best

**Comment by mrcrowl** [comment]
Have you experimented with the `math` options?

Search for math here
https://marketplace.visualstudio.com/items?itemName=mrcrowl.easy-less

**Comment by krsdcbl** [comment]
Thanks very much for the pointer, I must have completely overlooked that part of the readme! 
i guess it's just default setting that changed then
