### ISSUE TITLE
Cannot read property 'numerator' of undefined

### ISSUE THREAD

**Issue by elinkx-rko** [mrcrowl/vscode-easy-less#87]
Hi, 
when trying to save LESS file, this _Cannot read property 'numerator' of undefined_ error pops out and `@import` statement gets underlined (see screenshot). As a result of that I am unable to compile LESS files.

Any ideas of what might be the issue?

![image](https://user-images.githubusercontent.com/77731411/148179844-698dda32-0a2a-4518-8bc7-fd9dae7f162f.png)

**Comment by elinkx-rko** [comment]
Let me add that the very same code got compiled in the past (like a year ago or so) without problems.

**Comment by mrcrowl** [comment]
Hard to be sure without the source, but from what I've googled, it might be worth searching your less files for division `/`. 

Because `/` was introduced as valid css syntax in recent years (I don't recall where), certain math operations need to be wrapped with parentheses. 

e.g. `@n * 3 / 4` --> `(@n * 3 / 4)`

**Comment by elinkx-rko** [comment]
> Hard to be sure without the source, but from what I've googled, it might be worth searching your less files for division `/`.
> 
> Because `/` was introduced as valid css syntax in recent years (I don't recall where), certain math operations need to be wrapped with parentheses.
> 
> e.g. `@n * 3 / 4` --> `(@n * 3 / 4)`

Good idea, however, from what I see in the suspected file all equations are properly wrapped. 

![image](https://user-images.githubusercontent.com/77731411/148194865-d3d01d5c-fa1b-4cd9-9476-68801237b3a6.png)

**Comment by mrcrowl** [comment]
Closing until source is provided for further investigation.
