### ISSUE TITLE
Settings are totally ignored

### ISSUE THREAD

**Issue by Soahr** [mrcrowl/vscode-easy-less#88]
Hello,
Since today, the settings are completely ignored.
I tried to disable all others extensions and create a "workspace" settings file but nothing work and my css file always out fully compressed

**Comment by mrcrowl** [comment]
> Since today, the settings are completely ignored.

Just to confirm, was this working for you recently?

**Comment by Soahr** [comment]
Hi thanks for the response.
Yes it was working incredibly well until today.
I added some extensions about React recently but doesn't work when i disable it.
I'm gonna try complete VSCode reset to see if it change anything
