### ISSUE TITLE
Request: Publish to Open VSX

### ISSUE THREAD

**Issue by WfKe9vLwSvv7rN** [mrcrowl/vscode-easy-less#89]
It seems you have already done this for your other extension, Hg, so I will skip the details. I hope you will consider publishing Easy Less to Open VSX to make it easily accessible to VSCodium users and anyone else choosing not to use the Microsoft extension marketplace.

https://open-vsx.org/
https://github.com/mrcrowl/vscode-hg/issues/170
https://github.com/EclipseFdn/open-vsx.org/issues/496

**Comment by mrcrowl** [comment]
Yup. Can do

**Comment by mrcrowl** [comment]
Done: https://open-vsx.org/extension/mrcrowl/easy-less
