### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by bagaweb** [mrcrowl/vscode-easy-less#95]
This is the error appearing in problems after saving the .less file:

`Error evaluating function `unit`: the first argument to unit must be a number. Have you forgotten parenthesis?`

This is the less code giving the error on the last line:

```
.loop(@index) when(@index =< 12) {
  .nav-open li:nth-child(@{index}) {
    transition-delay: unit(@index / 10, s);
  }
  .loop(@index + 1);
}
.loop(0);
```

**Comment by mrcrowl** [comment]
I would recommend adding parentheses around @index / 10. I believe that is
causing the issue you're seeing.

This can be further controlled via the `math` settings.

**Comment by bagaweb** [comment]
Thank you very much, that did the trick!
